### ISSUE TITLE
How to configure the right host for dasexperimental? 

### ISSUE THREAD

**Issue by pwayner** [uscensusbureau/census2020-das-2010ddp#7]
Is there any good documentation for the best way to configure the code so it can find a way to  dasexperimental? 

 ~/Census/census2020-das-2010ddp/das_decennial$ python3 das20*.py configs/census_1940/ipums_1940.ini
=================================================
===    DAS RUN AT Wed Apr  1 07:48:09 2020    ===
=== UNKNOWN MISSION -- dasexperimental is down===
=================================================
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "das2020_driver.py", line 133, in <module>
    dashboard.das_log(mission_name + ' starting', extra={'start':'now()'})
  File "/home/pcw/Census/census2020-das-2010ddp/das_decennial/programs/dashboard.py", line 87, in das_log
    'instanceId': aws.instanceId()}, **extra}
  File "/home/pcw/Census/census2020-das-2010ddp/das_decennial/das_framework/ctools/aws.py", line 78, in instanceId
    return instance_identity()['instanceId']
  File "/home/pcw/Census/census2020-das-2010ddp/das_decennial/das_framework/ctools/aws.py", line 63, in instance_identity
    return get_url_json('http://169.254.169.254/latest/dynamic/instance-identity/document')
  File "/home/pcw/Census/census2020-das-2010ddp/das_decennial/das_framework/ctools/aws.py", line 57, in get_url_json
    return json.loads(get_url(url, **kwargs))
  File "/home/pcw/Census/census2020-das-2010ddp/das_decennial/das_framework/ctools/aws.py", line 53, in get_url
    with urllib.request.urlopen(url, context=context) as response:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 113] No route to host>

**Comment by simsong** [comment]
`dasexperimental` is an internal system at the US Census Bureau that we use for monitoring the execution of the DAS. This version of the code has an unfortunate dependency on `dasexperimental` which is used to create a mission name and to send log messages. You can simply insert a "return" statement as the first line of `das_log` to fix this problem.

**Comment by garfi303** [comment]
dasexperimental is an internal system at the US Census Bureau that we use for monitoring the execution of the DAS. This version of the code has an unfortunate dependency on dasexperimental which is used to create a mission name and to send log messages. You can simply insert a "return" statement as the first line of das_log to fix this problem.
